### PR TITLE
fix remove infinite loop

### PR DESCRIPTION
**Pull request by tanhauhau**
when adding the `this.remove()`, I tried to make the `index` in the `enter()` "consistent", as if the original `index` before any node being removed in the array.

However, little did I know that, if you try to remove more than one node in the node array, it will cause an infinite loop, because the subsequent `index` i use to splice the array is off by 1.

i wonder what is your thoughts on this,
- to have the `index` in the `enter()` to be the original index
- or the updated index after `splice` ?

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Oh, that's tricky... IIRC the original motivation for including the index was so that you could remove nodes yourself. Now that `this.remove()` is a thing (and can be implemented more reliably than it can be in userland) maybe we just shouldn't pass the index down?

Then again, there's one place in the Svelte codebase where the index is actually being used to insert nodes immediately after the current node. Short of adding an API for that (which would be pretty niche), I daresay that's an argument for `index` being the current index and not the original one. It also makes it easier to answer questions like 'is this the last node in the array?'

**Comment by Rich-Harris** [comment]
Opened an alternative PR, branched off of this one, that uses the current index rather than the original: #18

**Comment by tanhauhau** [comment]
I guess you are right, there's no hard reason why the index must be the original index.

**Comment by Rich-Harris** [comment]
Released 2.0.1

**Pull request merged**
